version: '3.7'

services:
  # web:
  #   container_name: gestioncredit_web
  #   restart: unless-stopped
  #   build: 
  #     context: ./docker
  #     dockerfile: Dockerfile-nginx
  #   volumes:
  #     - ./:/var/www/gestioncredit/:cached
  #   links:
  #     - php
  #   ports:
  #     - 8080:80

  # php:
  #   container_name: gestioncredit_php
  #   restart: unless-stopped
  #   depends_on:
  #     - database
  #   build: 
  #     context: ./docker 
  #     dockerfile: Dockerfile-php 
  #   # environment: 
  #   #   #- DATABASE_URL=mysql://root:root@db/docker_sf
  #   volumes: 
  #     - ./:/var/www/gestioncredit/:cached 

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: azad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: azad
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "9080:80"
      
  database:
    restart: unless-stopped
    container_name: gestioncredit_database
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: azad
      POSTGRES_PASSWORD: azad
      POSTGRES_USER: azad
    volumes:
      - database-data:/var/lib/postgresql/data
      # - database-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
      
volumes:
  database-data:  
    driver: local