version: '3.7'

services:
  web:
    restart: unless-stopped
    build: 
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/gestioncredit/:cached
    links:
      - php
    ports:
      - 8080:80

  php:
    restart: unless-stopped
    depends_on:
      - database
    build: 
      context: ./docker 
      dockerfile: Dockerfile-php 
    # environment: 
    #   #- DATABASE_URL=mysql://root:root@db/docker_sf
    volumes: 
      - ./:/var/www/gestioncredit/:cached 

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: azad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: azad
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "9080:80"
      
  database:
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: azad
      POSTGRES_PASSWORD: azad
      POSTGRES_USER: azad
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes:
  database-data:  
    driver: local