<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230907052513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE agency_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE article_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attestation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attestation_approval_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attestation_rejection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contact_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contract_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credit_approval_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credit_rejection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE credit_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE divorced_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evaluation_gage_section_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evaluation_gage_service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gage_credit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gage_folder_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE general_content_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gold_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE login_attempt_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE married_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE matrimonial_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mounting_credit_folder_service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mounting_section_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parameter_in_description_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE portfolio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE renawal_gage_credit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE signature_label_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE single_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE widower_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE agency (id INT NOT NULL, manager_id INT DEFAULT NULL, label VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_70C0C6E6783E3463 ON agency (manager_id)');
        $this->addSql('CREATE TABLE article (id INT NOT NULL, title INT NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE attestation (id INT NOT NULL, client_id INT DEFAULT NULL, evaluator_id INT DEFAULT NULL, credit_type_id INT DEFAULT NULL, folder_id INT DEFAULT NULL, cancelled_by_employe_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, evaluator_description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_cause VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_326EC63F19EB6921 ON attestation (client_id)');
        $this->addSql('CREATE INDEX IDX_326EC63F43575BE2 ON attestation (evaluator_id)');
        $this->addSql('CREATE INDEX IDX_326EC63FFFC8EBBC ON attestation (credit_type_id)');
        $this->addSql('CREATE INDEX IDX_326EC63F162CB942 ON attestation (folder_id)');
        $this->addSql('CREATE INDEX IDX_326EC63FAE255D4 ON attestation (cancelled_by_employe_id)');
        $this->addSql('CREATE TABLE attestation_approval (id INT NOT NULL, attestation_id INT DEFAULT NULL, supervisor_id INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E75A00E67EDC5B38 ON attestation_approval (attestation_id)');
        $this->addSql('CREATE INDEX IDX_E75A00E619E9AC5F ON attestation_approval (supervisor_id)');
        $this->addSql('CREATE TABLE attestation_rejection (id INT NOT NULL, attestation_id INT DEFAULT NULL, supervisor_id INT DEFAULT NULL, cause VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_72A29367EDC5B38 ON attestation_rejection (attestation_id)');
        $this->addSql('CREATE INDEX IDX_72A293619E9AC5F ON attestation_rejection (supervisor_id)');
        $this->addSql('CREATE TABLE contact (id INT NOT NULL, telephone VARCHAR(50) DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C62E638450FF010 ON contact (telephone)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C62E638E7927C74 ON contact (email)');
        $this->addSql('CREATE TABLE contract (id INT NOT NULL, content_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E98F285984A0A3ED ON contract (content_id)');
        $this->addSql('CREATE TABLE articles_gage_contracts (contract_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY(contract_id, article_id))');
        $this->addSql('CREATE INDEX IDX_BE6045B42576E0FD ON articles_gage_contracts (contract_id)');
        $this->addSql('CREATE INDEX IDX_BE6045B47294869C ON articles_gage_contracts (article_id)');
        $this->addSql('CREATE TABLE gage_contracts_signature_labels (contract_id INT NOT NULL, signature_label_id INT NOT NULL, PRIMARY KEY(contract_id, signature_label_id))');
        $this->addSql('CREATE INDEX IDX_A0D3294E2576E0FD ON gage_contracts_signature_labels (contract_id)');
        $this->addSql('CREATE INDEX IDX_A0D3294E80D5A988 ON gage_contracts_signature_labels (signature_label_id)');
        $this->addSql('CREATE TABLE articles_death_solidarirty_contracts (contract_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY(contract_id, article_id))');
        $this->addSql('CREATE INDEX IDX_576712792576E0FD ON articles_death_solidarirty_contracts (contract_id)');
        $this->addSql('CREATE INDEX IDX_576712797294869C ON articles_death_solidarirty_contracts (article_id)');
        $this->addSql('CREATE TABLE death_solidarity_contracts_signature_labels (contract_id INT NOT NULL, signature_label_id INT NOT NULL, PRIMARY KEY(contract_id, signature_label_id))');
        $this->addSql('CREATE INDEX IDX_8547867D2576E0FD ON death_solidarity_contracts_signature_labels (contract_id)');
        $this->addSql('CREATE INDEX IDX_8547867D80D5A988 ON death_solidarity_contracts_signature_labels (signature_label_id)');
        $this->addSql('CREATE TABLE corporate (id INT NOT NULL, created_location_id INT DEFAULT NULL, central_location_id INT DEFAULT NULL, legal_form VARCHAR(255) NOT NULL, activity_domain VARCHAR(255) NOT NULL, comericial_registry VARCHAR(255) NOT NULL, folio INT NOT NULL, membership_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F33D7A2F45607D0 ON corporate (comericial_registry)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F33D7A29BEA0CC6 ON corporate (folio)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F33D7A2A73D36F9 ON corporate (created_location_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F33D7A220111F93 ON corporate (central_location_id)');
        $this->addSql('CREATE TABLE corporates_managers (corporate_id INT NOT NULL, manager_id INT NOT NULL, PRIMARY KEY(corporate_id, manager_id))');
        $this->addSql('CREATE INDEX IDX_D86BA980CD147EEF ON corporates_managers (corporate_id)');
        $this->addSql('CREATE INDEX IDX_D86BA980783E3463 ON corporates_managers (manager_id)');
        $this->addSql('CREATE TABLE credit_approval (id INT NOT NULL, approving_id INT DEFAULT NULL, credit_id INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD0B2C15AE67C910 ON credit_approval (approving_id)');
        $this->addSql('CREATE INDEX IDX_BD0B2C15CE062FF9 ON credit_approval (credit_id)');
        $this->addSql('CREATE TABLE credit_rejection (id INT NOT NULL, approving_id INT DEFAULT NULL, credit_id INT DEFAULT NULL, cause VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23C4DBBCAE67C910 ON credit_rejection (approving_id)');
        $this->addSql('CREATE INDEX IDX_23C4DBBCCE062FF9 ON credit_rejection (credit_id)');
        $this->addSql('CREATE TABLE credit_type (id INT NOT NULL, section_id INT DEFAULT NULL, label VARCHAR(100) NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B1CE8145E237E06 ON credit_type (name)');
        $this->addSql('CREATE INDEX IDX_8B1CE814D823E37A ON credit_type (section_id)');
        $this->addSql('CREATE TABLE divorced (id INT NOT NULL, matrimonial_status_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_304651934B93C697 ON divorced (matrimonial_status_id)');
        $this->addSql('CREATE TABLE employee (id INT NOT NULL, evaluation_section_id INT DEFAULT NULL, mounting_section_id INT DEFAULT NULL, fullname VARCHAR(180) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5D9F75A13224A488 ON employee (evaluation_section_id)');
        $this->addSql('CREATE INDEX IDX_5D9F75A1C859C8A6 ON employee (mounting_section_id)');
        $this->addSql('CREATE TABLE evaluation_gage_section (id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE agents_gage_sections (section_id INT NOT NULL, gage_evaluator_id INT NOT NULL, PRIMARY KEY(section_id, gage_evaluator_id))');
        $this->addSql('CREATE INDEX IDX_5514D516D823E37A ON agents_gage_sections (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5514D516CA88129A ON agents_gage_sections (gage_evaluator_id)');
        $this->addSql('CREATE TABLE supervisors_gage_sections (section_id INT NOT NULL, gage_supervisor_id INT NOT NULL, PRIMARY KEY(section_id, gage_supervisor_id))');
        $this->addSql('CREATE INDEX IDX_38AE7304D823E37A ON supervisors_gage_sections (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_38AE730447BE8A18 ON supervisors_gage_sections (gage_supervisor_id)');
        $this->addSql('CREATE TABLE evaluation_gage_service (id INT NOT NULL, agency_id INT DEFAULT NULL, section_id INT DEFAULT NULL, service_name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4FC83F9060CAEA ON evaluation_gage_service (service_name)');
        $this->addSql('CREATE INDEX IDX_AD4FC83FCDEADB2A ON evaluation_gage_service (agency_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4FC83FD823E37A ON evaluation_gage_service (section_id)');
        $this->addSql('CREATE TABLE gage_credit (id INT NOT NULL, attestation_id INT DEFAULT NULL, agent_id INT DEFAULT NULL, cancelled_by_employe_id INT DEFAULT NULL, capital INT NOT NULL, id_adbanking_folder INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration INT NOT NULL, interest DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_cause VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4DA49A87EDC5B38 ON gage_credit (attestation_id)');
        $this->addSql('CREATE INDEX IDX_F4DA49A83414710B ON gage_credit (agent_id)');
        $this->addSql('CREATE INDEX IDX_F4DA49A8AE255D4 ON gage_credit (cancelled_by_employe_id)');
        $this->addSql('CREATE TABLE contracts_credits (credit_id INT NOT NULL, contract_id INT NOT NULL, PRIMARY KEY(credit_id, contract_id))');
        $this->addSql('CREATE INDEX IDX_C42D5A4BCE062FF9 ON contracts_credits (credit_id)');
        $this->addSql('CREATE INDEX IDX_C42D5A4B2576E0FD ON contracts_credits (contract_id)');
        $this->addSql('CREATE TABLE gage_folder (id INT NOT NULL, credit_id INT DEFAULT NULL, portfolio_id INT DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B92E9BCE062FF9 ON gage_folder (credit_id)');
        $this->addSql('CREATE INDEX IDX_4B92E9BB96B5643 ON gage_folder (portfolio_id)');
        $this->addSql('CREATE TABLE general_content (id INT NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE gold (id INT NOT NULL, attestation_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, quantity INT DEFAULT 1 NOT NULL, carrat INT NOT NULL, unit_price INT NOT NULL, weight INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_47A91D517EDC5B38 ON gold (attestation_id)');
        $this->addSql('CREATE TABLE individual (id INT NOT NULL, birth_location_id INT DEFAULT NULL, matrimonial_status_id INT DEFAULT NULL, nick_name VARCHAR(100) DEFAULT NULL, gender VARCHAR(1) NOT NULL, profession VARCHAR(255) DEFAULT NULL, brith_day TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nin INT NOT NULL, folio INT NOT NULL, membership_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8793FC17A33DA389 ON individual (nin)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8793FC179BEA0CC6 ON individual (folio)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8793FC17A0C0BE62 ON individual (birth_location_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8793FC174B93C697 ON individual (matrimonial_status_id)');
        $this->addSql('CREATE TABLE location (id INT NOT NULL, region VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, neighborhood VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE login_attempt (id INT NOT NULL, user_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C11C1BA76ED395 ON login_attempt (user_id)');
        $this->addSql('CREATE TABLE married (id INT NOT NULL, matrimonial_status_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3D23F104B93C697 ON married (matrimonial_status_id)');
        $this->addSql('CREATE TABLE married_person (married_id INT NOT NULL, spouse_id INT NOT NULL, PRIMARY KEY(married_id, spouse_id))');
        $this->addSql('CREATE INDEX IDX_68E2DDAC4A64FF67 ON married_person (married_id)');
        $this->addSql('CREATE INDEX IDX_68E2DDAC8EEC5B5C ON married_person (spouse_id)');
        $this->addSql('CREATE TABLE matrimonial_status (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mounting_credit_folder_service (id INT NOT NULL, agency_id INT DEFAULT NULL, section_id INT DEFAULT NULL, service_name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_424749A9060CAEA ON mounting_credit_folder_service (service_name)');
        $this->addSql('CREATE INDEX IDX_424749ACDEADB2A ON mounting_credit_folder_service (agency_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_424749AD823E37A ON mounting_credit_folder_service (section_id)');
        $this->addSql('CREATE TABLE mounting_section (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE agents_mounting_sections (section_id INT NOT NULL, credit_agent_id INT NOT NULL, PRIMARY KEY(section_id, credit_agent_id))');
        $this->addSql('CREATE INDEX IDX_B33D4BB8D823E37A ON agents_mounting_sections (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B33D4BB89FFFC835 ON agents_mounting_sections (credit_agent_id)');
        $this->addSql('CREATE TABLE supervisors_mounting_sections (section_id INT NOT NULL, credit_supervisor_id INT NOT NULL, PRIMARY KEY(section_id, credit_supervisor_id))');
        $this->addSql('CREATE INDEX IDX_B9F1AEA9D823E37A ON supervisors_mounting_sections (section_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9F1AEA98FC6F1CB ON supervisors_mounting_sections (credit_supervisor_id)');
        $this->addSql('CREATE TABLE notification (id INT NOT NULL, user_id INT DEFAULT NULL, message VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, channel VARCHAR(255) DEFAULT NULL, target VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE parameter_in_description (id INT NOT NULL, article_id INT DEFAULT NULL, position INT NOT NULL, key VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3464ADC37294869C ON parameter_in_description (article_id)');
        $this->addSql('CREATE TABLE person (id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE locations_persons (person_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY(person_id, location_id))');
        $this->addSql('CREATE INDEX IDX_638475FB217BBB47 ON locations_persons (person_id)');
        $this->addSql('CREATE INDEX IDX_638475FB64D218E ON locations_persons (location_id)');
        $this->addSql('CREATE TABLE contacts_persons (person_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY(person_id, contact_id))');
        $this->addSql('CREATE INDEX IDX_28F4CB8E217BBB47 ON contacts_persons (person_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_28F4CB8EE7A1254A ON contacts_persons (contact_id)');
        $this->addSql('CREATE TABLE portfolio (id INT NOT NULL, client_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9ED106219EB6921 ON portfolio (client_id)');
        $this->addSql('CREATE TABLE renawal_gage_credit (id INT NOT NULL, old_credit_id INT DEFAULT NULL, new_credit_id INT DEFAULT NULL, folder_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9DF91E48BB26B48 ON renawal_gage_credit (old_credit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9DF91E4FC992A96 ON renawal_gage_credit (new_credit_id)');
        $this->addSql('CREATE INDEX IDX_B9DF91E4162CB942 ON renawal_gage_credit (folder_id)');
        $this->addSql('CREATE TABLE signature_label (id INT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE single (id INT NOT NULL, matrimonial_status_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CAA727194B93C697 ON single (matrimonial_status_id)');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notification_read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE widower (id INT NOT NULL, matrimonial_status_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6390A8B64B93C697 ON widower (matrimonial_status_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE agency ADD CONSTRAINT FK_70C0C6E6783E3463 FOREIGN KEY (manager_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F19EB6921 FOREIGN KEY (client_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F43575BE2 FOREIGN KEY (evaluator_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63FFFC8EBBC FOREIGN KEY (credit_type_id) REFERENCES credit_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F162CB942 FOREIGN KEY (folder_id) REFERENCES gage_folder (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63FAE255D4 FOREIGN KEY (cancelled_by_employe_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_approval ADD CONSTRAINT FK_E75A00E67EDC5B38 FOREIGN KEY (attestation_id) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_approval ADD CONSTRAINT FK_E75A00E619E9AC5F FOREIGN KEY (supervisor_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_rejection ADD CONSTRAINT FK_72A29367EDC5B38 FOREIGN KEY (attestation_id) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_rejection ADD CONSTRAINT FK_72A293619E9AC5F FOREIGN KEY (supervisor_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F285984A0A3ED FOREIGN KEY (content_id) REFERENCES general_content (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles_gage_contracts ADD CONSTRAINT FK_BE6045B42576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles_gage_contracts ADD CONSTRAINT FK_BE6045B47294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_contracts_signature_labels ADD CONSTRAINT FK_A0D3294E2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_contracts_signature_labels ADD CONSTRAINT FK_A0D3294E80D5A988 FOREIGN KEY (signature_label_id) REFERENCES signature_label (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles_death_solidarirty_contracts ADD CONSTRAINT FK_576712792576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles_death_solidarirty_contracts ADD CONSTRAINT FK_576712797294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE death_solidarity_contracts_signature_labels ADD CONSTRAINT FK_8547867D2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE death_solidarity_contracts_signature_labels ADD CONSTRAINT FK_8547867D80D5A988 FOREIGN KEY (signature_label_id) REFERENCES signature_label (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporate ADD CONSTRAINT FK_1F33D7A2A73D36F9 FOREIGN KEY (created_location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporate ADD CONSTRAINT FK_1F33D7A220111F93 FOREIGN KEY (central_location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporate ADD CONSTRAINT FK_1F33D7A2BF396750 FOREIGN KEY (id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporates_managers ADD CONSTRAINT FK_D86BA980CD147EEF FOREIGN KEY (corporate_id) REFERENCES corporate (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE corporates_managers ADD CONSTRAINT FK_D86BA980783E3463 FOREIGN KEY (manager_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_approval ADD CONSTRAINT FK_BD0B2C15AE67C910 FOREIGN KEY (approving_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_approval ADD CONSTRAINT FK_BD0B2C15CE062FF9 FOREIGN KEY (credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_rejection ADD CONSTRAINT FK_23C4DBBCAE67C910 FOREIGN KEY (approving_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_rejection ADD CONSTRAINT FK_23C4DBBCCE062FF9 FOREIGN KEY (credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit_type ADD CONSTRAINT FK_8B1CE814D823E37A FOREIGN KEY (section_id) REFERENCES mounting_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE divorced ADD CONSTRAINT FK_304651934B93C697 FOREIGN KEY (matrimonial_status_id) REFERENCES matrimonial_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A13224A488 FOREIGN KEY (evaluation_section_id) REFERENCES evaluation_gage_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1C859C8A6 FOREIGN KEY (mounting_section_id) REFERENCES mounting_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1BF396750 FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_gage_sections ADD CONSTRAINT FK_5514D516D823E37A FOREIGN KEY (section_id) REFERENCES evaluation_gage_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_gage_sections ADD CONSTRAINT FK_5514D516CA88129A FOREIGN KEY (gage_evaluator_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE supervisors_gage_sections ADD CONSTRAINT FK_38AE7304D823E37A FOREIGN KEY (section_id) REFERENCES evaluation_gage_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE supervisors_gage_sections ADD CONSTRAINT FK_38AE730447BE8A18 FOREIGN KEY (gage_supervisor_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evaluation_gage_service ADD CONSTRAINT FK_AD4FC83FCDEADB2A FOREIGN KEY (agency_id) REFERENCES agency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evaluation_gage_service ADD CONSTRAINT FK_AD4FC83FD823E37A FOREIGN KEY (section_id) REFERENCES evaluation_gage_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_credit ADD CONSTRAINT FK_F4DA49A87EDC5B38 FOREIGN KEY (attestation_id) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_credit ADD CONSTRAINT FK_F4DA49A83414710B FOREIGN KEY (agent_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_credit ADD CONSTRAINT FK_F4DA49A8AE255D4 FOREIGN KEY (cancelled_by_employe_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_credits ADD CONSTRAINT FK_C42D5A4BCE062FF9 FOREIGN KEY (credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contracts_credits ADD CONSTRAINT FK_C42D5A4B2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_folder ADD CONSTRAINT FK_4B92E9BCE062FF9 FOREIGN KEY (credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gage_folder ADD CONSTRAINT FK_4B92E9BB96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gold ADD CONSTRAINT FK_47A91D517EDC5B38 FOREIGN KEY (attestation_id) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE individual ADD CONSTRAINT FK_8793FC17A0C0BE62 FOREIGN KEY (birth_location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE individual ADD CONSTRAINT FK_8793FC174B93C697 FOREIGN KEY (matrimonial_status_id) REFERENCES matrimonial_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE individual ADD CONSTRAINT FK_8793FC17BF396750 FOREIGN KEY (id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE login_attempt ADD CONSTRAINT FK_8C11C1BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE married ADD CONSTRAINT FK_E3D23F104B93C697 FOREIGN KEY (matrimonial_status_id) REFERENCES matrimonial_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE married_person ADD CONSTRAINT FK_68E2DDAC4A64FF67 FOREIGN KEY (married_id) REFERENCES married (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE married_person ADD CONSTRAINT FK_68E2DDAC8EEC5B5C FOREIGN KEY (spouse_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mounting_credit_folder_service ADD CONSTRAINT FK_424749ACDEADB2A FOREIGN KEY (agency_id) REFERENCES agency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mounting_credit_folder_service ADD CONSTRAINT FK_424749AD823E37A FOREIGN KEY (section_id) REFERENCES mounting_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_mounting_sections ADD CONSTRAINT FK_B33D4BB8D823E37A FOREIGN KEY (section_id) REFERENCES mounting_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_mounting_sections ADD CONSTRAINT FK_B33D4BB89FFFC835 FOREIGN KEY (credit_agent_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE supervisors_mounting_sections ADD CONSTRAINT FK_B9F1AEA9D823E37A FOREIGN KEY (section_id) REFERENCES mounting_section (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE supervisors_mounting_sections ADD CONSTRAINT FK_B9F1AEA98FC6F1CB FOREIGN KEY (credit_supervisor_id) REFERENCES employee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameter_in_description ADD CONSTRAINT FK_3464ADC37294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE locations_persons ADD CONSTRAINT FK_638475FB217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE locations_persons ADD CONSTRAINT FK_638475FB64D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contacts_persons ADD CONSTRAINT FK_28F4CB8E217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contacts_persons ADD CONSTRAINT FK_28F4CB8EE7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT FK_A9ED106219EB6921 FOREIGN KEY (client_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE renawal_gage_credit ADD CONSTRAINT FK_B9DF91E48BB26B48 FOREIGN KEY (old_credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE renawal_gage_credit ADD CONSTRAINT FK_B9DF91E4FC992A96 FOREIGN KEY (new_credit_id) REFERENCES gage_credit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE renawal_gage_credit ADD CONSTRAINT FK_B9DF91E4162CB942 FOREIGN KEY (folder_id) REFERENCES gage_folder (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE single ADD CONSTRAINT FK_CAA727194B93C697 FOREIGN KEY (matrimonial_status_id) REFERENCES matrimonial_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE widower ADD CONSTRAINT FK_6390A8B64B93C697 FOREIGN KEY (matrimonial_status_id) REFERENCES matrimonial_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE agency_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE article_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attestation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attestation_approval_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attestation_rejection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contact_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contract_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credit_approval_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credit_rejection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE credit_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE divorced_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evaluation_gage_section_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evaluation_gage_service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gage_credit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gage_folder_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE general_content_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gold_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE login_attempt_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE married_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE matrimonial_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mounting_credit_folder_service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mounting_section_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parameter_in_description_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE portfolio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE renawal_gage_credit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE signature_label_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE single_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE widower_id_seq CASCADE');
        $this->addSql('ALTER TABLE agency DROP CONSTRAINT FK_70C0C6E6783E3463');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F19EB6921');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F43575BE2');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63FFFC8EBBC');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F162CB942');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63FAE255D4');
        $this->addSql('ALTER TABLE attestation_approval DROP CONSTRAINT FK_E75A00E67EDC5B38');
        $this->addSql('ALTER TABLE attestation_approval DROP CONSTRAINT FK_E75A00E619E9AC5F');
        $this->addSql('ALTER TABLE attestation_rejection DROP CONSTRAINT FK_72A29367EDC5B38');
        $this->addSql('ALTER TABLE attestation_rejection DROP CONSTRAINT FK_72A293619E9AC5F');
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F285984A0A3ED');
        $this->addSql('ALTER TABLE articles_gage_contracts DROP CONSTRAINT FK_BE6045B42576E0FD');
        $this->addSql('ALTER TABLE articles_gage_contracts DROP CONSTRAINT FK_BE6045B47294869C');
        $this->addSql('ALTER TABLE gage_contracts_signature_labels DROP CONSTRAINT FK_A0D3294E2576E0FD');
        $this->addSql('ALTER TABLE gage_contracts_signature_labels DROP CONSTRAINT FK_A0D3294E80D5A988');
        $this->addSql('ALTER TABLE articles_death_solidarirty_contracts DROP CONSTRAINT FK_576712792576E0FD');
        $this->addSql('ALTER TABLE articles_death_solidarirty_contracts DROP CONSTRAINT FK_576712797294869C');
        $this->addSql('ALTER TABLE death_solidarity_contracts_signature_labels DROP CONSTRAINT FK_8547867D2576E0FD');
        $this->addSql('ALTER TABLE death_solidarity_contracts_signature_labels DROP CONSTRAINT FK_8547867D80D5A988');
        $this->addSql('ALTER TABLE corporate DROP CONSTRAINT FK_1F33D7A2A73D36F9');
        $this->addSql('ALTER TABLE corporate DROP CONSTRAINT FK_1F33D7A220111F93');
        $this->addSql('ALTER TABLE corporate DROP CONSTRAINT FK_1F33D7A2BF396750');
        $this->addSql('ALTER TABLE corporates_managers DROP CONSTRAINT FK_D86BA980CD147EEF');
        $this->addSql('ALTER TABLE corporates_managers DROP CONSTRAINT FK_D86BA980783E3463');
        $this->addSql('ALTER TABLE credit_approval DROP CONSTRAINT FK_BD0B2C15AE67C910');
        $this->addSql('ALTER TABLE credit_approval DROP CONSTRAINT FK_BD0B2C15CE062FF9');
        $this->addSql('ALTER TABLE credit_rejection DROP CONSTRAINT FK_23C4DBBCAE67C910');
        $this->addSql('ALTER TABLE credit_rejection DROP CONSTRAINT FK_23C4DBBCCE062FF9');
        $this->addSql('ALTER TABLE credit_type DROP CONSTRAINT FK_8B1CE814D823E37A');
        $this->addSql('ALTER TABLE divorced DROP CONSTRAINT FK_304651934B93C697');
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A13224A488');
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1C859C8A6');
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1BF396750');
        $this->addSql('ALTER TABLE agents_gage_sections DROP CONSTRAINT FK_5514D516D823E37A');
        $this->addSql('ALTER TABLE agents_gage_sections DROP CONSTRAINT FK_5514D516CA88129A');
        $this->addSql('ALTER TABLE supervisors_gage_sections DROP CONSTRAINT FK_38AE7304D823E37A');
        $this->addSql('ALTER TABLE supervisors_gage_sections DROP CONSTRAINT FK_38AE730447BE8A18');
        $this->addSql('ALTER TABLE evaluation_gage_service DROP CONSTRAINT FK_AD4FC83FCDEADB2A');
        $this->addSql('ALTER TABLE evaluation_gage_service DROP CONSTRAINT FK_AD4FC83FD823E37A');
        $this->addSql('ALTER TABLE gage_credit DROP CONSTRAINT FK_F4DA49A87EDC5B38');
        $this->addSql('ALTER TABLE gage_credit DROP CONSTRAINT FK_F4DA49A83414710B');
        $this->addSql('ALTER TABLE gage_credit DROP CONSTRAINT FK_F4DA49A8AE255D4');
        $this->addSql('ALTER TABLE contracts_credits DROP CONSTRAINT FK_C42D5A4BCE062FF9');
        $this->addSql('ALTER TABLE contracts_credits DROP CONSTRAINT FK_C42D5A4B2576E0FD');
        $this->addSql('ALTER TABLE gage_folder DROP CONSTRAINT FK_4B92E9BCE062FF9');
        $this->addSql('ALTER TABLE gage_folder DROP CONSTRAINT FK_4B92E9BB96B5643');
        $this->addSql('ALTER TABLE gold DROP CONSTRAINT FK_47A91D517EDC5B38');
        $this->addSql('ALTER TABLE individual DROP CONSTRAINT FK_8793FC17A0C0BE62');
        $this->addSql('ALTER TABLE individual DROP CONSTRAINT FK_8793FC174B93C697');
        $this->addSql('ALTER TABLE individual DROP CONSTRAINT FK_8793FC17BF396750');
        $this->addSql('ALTER TABLE login_attempt DROP CONSTRAINT FK_8C11C1BA76ED395');
        $this->addSql('ALTER TABLE married DROP CONSTRAINT FK_E3D23F104B93C697');
        $this->addSql('ALTER TABLE married_person DROP CONSTRAINT FK_68E2DDAC4A64FF67');
        $this->addSql('ALTER TABLE married_person DROP CONSTRAINT FK_68E2DDAC8EEC5B5C');
        $this->addSql('ALTER TABLE mounting_credit_folder_service DROP CONSTRAINT FK_424749ACDEADB2A');
        $this->addSql('ALTER TABLE mounting_credit_folder_service DROP CONSTRAINT FK_424749AD823E37A');
        $this->addSql('ALTER TABLE agents_mounting_sections DROP CONSTRAINT FK_B33D4BB8D823E37A');
        $this->addSql('ALTER TABLE agents_mounting_sections DROP CONSTRAINT FK_B33D4BB89FFFC835');
        $this->addSql('ALTER TABLE supervisors_mounting_sections DROP CONSTRAINT FK_B9F1AEA9D823E37A');
        $this->addSql('ALTER TABLE supervisors_mounting_sections DROP CONSTRAINT FK_B9F1AEA98FC6F1CB');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE parameter_in_description DROP CONSTRAINT FK_3464ADC37294869C');
        $this->addSql('ALTER TABLE locations_persons DROP CONSTRAINT FK_638475FB217BBB47');
        $this->addSql('ALTER TABLE locations_persons DROP CONSTRAINT FK_638475FB64D218E');
        $this->addSql('ALTER TABLE contacts_persons DROP CONSTRAINT FK_28F4CB8E217BBB47');
        $this->addSql('ALTER TABLE contacts_persons DROP CONSTRAINT FK_28F4CB8EE7A1254A');
        $this->addSql('ALTER TABLE portfolio DROP CONSTRAINT FK_A9ED106219EB6921');
        $this->addSql('ALTER TABLE renawal_gage_credit DROP CONSTRAINT FK_B9DF91E48BB26B48');
        $this->addSql('ALTER TABLE renawal_gage_credit DROP CONSTRAINT FK_B9DF91E4FC992A96');
        $this->addSql('ALTER TABLE renawal_gage_credit DROP CONSTRAINT FK_B9DF91E4162CB942');
        $this->addSql('ALTER TABLE single DROP CONSTRAINT FK_CAA727194B93C697');
        $this->addSql('ALTER TABLE widower DROP CONSTRAINT FK_6390A8B64B93C697');
        $this->addSql('DROP TABLE agency');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE attestation');
        $this->addSql('DROP TABLE attestation_approval');
        $this->addSql('DROP TABLE attestation_rejection');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE articles_gage_contracts');
        $this->addSql('DROP TABLE gage_contracts_signature_labels');
        $this->addSql('DROP TABLE articles_death_solidarirty_contracts');
        $this->addSql('DROP TABLE death_solidarity_contracts_signature_labels');
        $this->addSql('DROP TABLE corporate');
        $this->addSql('DROP TABLE corporates_managers');
        $this->addSql('DROP TABLE credit_approval');
        $this->addSql('DROP TABLE credit_rejection');
        $this->addSql('DROP TABLE credit_type');
        $this->addSql('DROP TABLE divorced');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE evaluation_gage_section');
        $this->addSql('DROP TABLE agents_gage_sections');
        $this->addSql('DROP TABLE supervisors_gage_sections');
        $this->addSql('DROP TABLE evaluation_gage_service');
        $this->addSql('DROP TABLE gage_credit');
        $this->addSql('DROP TABLE contracts_credits');
        $this->addSql('DROP TABLE gage_folder');
        $this->addSql('DROP TABLE general_content');
        $this->addSql('DROP TABLE gold');
        $this->addSql('DROP TABLE individual');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE login_attempt');
        $this->addSql('DROP TABLE married');
        $this->addSql('DROP TABLE married_person');
        $this->addSql('DROP TABLE matrimonial_status');
        $this->addSql('DROP TABLE mounting_credit_folder_service');
        $this->addSql('DROP TABLE mounting_section');
        $this->addSql('DROP TABLE agents_mounting_sections');
        $this->addSql('DROP TABLE supervisors_mounting_sections');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE parameter_in_description');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE locations_persons');
        $this->addSql('DROP TABLE contacts_persons');
        $this->addSql('DROP TABLE portfolio');
        $this->addSql('DROP TABLE renawal_gage_credit');
        $this->addSql('DROP TABLE signature_label');
        $this->addSql('DROP TABLE single');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE widower');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
